### ISSUE TITLE
Listener functions with optional parameters

### ISSUE THREAD

**Issue by nevf** [mantoni/hub.js#2]
@mantoni First let me say hub.js is great, especially the ability for listeners to return values to publishers. I haven't seen this in any other pub/sub package and it really helps with loose coupling.

I've found a small problem though. If I have a listener:

````
hub.on('event', function( p1, p2, p3 ){});
````

and use

````
hub.emit('event');
````

In this specific case the listener function's parameters are all optional.
But the the listener function gets: ````p1=undefined, p2=undefined, p3 - callback.````

I've looked at hub.js and the code in emit():
````
    var async = fn.length > argsLength;
    if (async) {
      args[fn.length - 1] = listener();
    }
````
is the the source of the problem. I'm wondering if this can be made a bit smarter to handle the case where listener function params are optional. 

Neville

**Comment by mantoni** [comment]
The refactoring is now completed. Sorry that it took 1.5 years. There is still no solution, but the place where this could go is now [glob-events.js](https://github.com/mantoni/glob-events.js). The API and also the way it's implemented will allow to put this in.
