### ISSUE TITLE
Possible to get event names on listener?

### ISSUE THREAD

**Issue by CreativeCactus** [mantoni/hub.js#4]
Hi, nice library, I was just wondering, given:
```
hub.on('debug.**',e=>{
  name='debug.??.??'
  console.log(name,e)
})
```

Any way to get the event name? Perhaps some kind of `this` magic, or a property on the first/last arg?
Thanks

**Comment by mantoni** [comment]
You're looking for [`this` in filter and listener](https://github.com/mantoni/hub.js#this-in-filter-and-listener). It's `this.event` for the event name and `this.args` for the arguments.
